name: Birdsong
options:
  deploymentTarget:
    iOS: 8.0
targets:
  Birdsong:
    type: framework
    platform: iOS
    sources: Sources
    scheme:
      gatherCoverageData: true
      testTargets:
        - BirdsongTests
    dependencies:
      - carthage: Starscream
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.birdsong.birdsong
        INFOPLIST_FILE: Configs/Birdsong.plist
  BirdsongTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests
    dependencies:
      - target: Birdsong
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.birdsong.birdsongtests
        INFOPLIST_FILE: Configs/BirdsongTests.plist
  Example:
    type: application
    platform: iOS
    sources: Example
    dependencies:
      - target: Birdsong
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rmalhotra.Example
